Config:
  look_back: 60
  start: 2015-01-03
  end: 2019-09-01
  company: ADBE
GPR:
  kernel:
    constant: 63.0
    length_scale: 1
    length_scale_bounds:
      - 1.0e-2
      - 100.0
  alpha: 1.0e-6
  n_restarts_optimizer: 6
  normalize_y: True
Train:
  dev_size: 0.2
Test:
  start: 2019-09-02
  end: 2020-04-01